const UserActionTypes = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
  USER_FACEBOOK_LOGIN_REQUEST: "USER_FACEBOOK_LOGIN_REQUEST",
  USER_FACEBOOK_LOGIN_SUCCESS: "USER_FACEBOOK_LOGIN_SUCCESS",
  USER_FACEBOOK_LOGIN_FAIL: "USER_FACEBOOK_LOGIN_FAIL",
  USER_GOOGLE_LOGIN_REQUEST: "USER_GOOGLE_LOGIN_REQUEST",
  USER_GOOGLE_LOGIN_SUCCESS: "USER_GOOGLE_LOGIN_SUCCESS",
  USER_GOOGLE_LOGIN_FAIL: "USER_GOOGLE_LOGIN_FAIL",
  USER_LOGOUT: "USER_LOGOUT",
};

export default UserActionTypes;
